// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zeta-phase2/MeetingDetailAnalysis.tsx": () => import("../components/mockups/zeta-phase2/MeetingDetailAnalysis.tsx"),
  "./components/mockups/zeta-phase2/RecordResult.tsx": () => import("../components/mockups/zeta-phase2/RecordResult.tsx")
};
